name: Python-Project-50

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run linter
        run: make lint
      # - name: SonarQubeScan
      #   uses: SonarSource/sonarqube-scan-action@v5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=hexlet-boilerplates_python-package
      #       -Dsonar.organization=hexlet-boilerplates
      #       -Dsonar.python.coverage.reportPaths=coverage.xml