name: Python-Project-50 CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run linter and tests
      run: |
        make check

    - name: Run test coverage
      run: |
          make test-coverage
          
    - name: SonarQubeScan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
         args: >
          -Dsonar.projectKey=gendiff
          -Dsonar.sources=gendiff
          -Dsonar.python.coverage.reportPaths=coverage.xml