name: Python-Project-50 CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Run linter
      run: |
        pip install ruff
        ruff check gendiff/
        
    - name: Run tests
      run: |
        pytest tests/
